/*
 * Copyright 2026 Nicolas Cassan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export {
  formatBriqueCapabilityIntention,
  formatBriqueCapabilityParams,
  getBriqueCapabilityContract,
  isKnownBriqueCapability,
  listBriqueCapabilityContracts,
  parseBriqueCapabilityResponse,
  type CapabilityContract,
  type CapabilityPayloadMap,
  type KnownCapability,
  type FormatCapabilityInput,
  type ParsedBriqueResponse,
  type ParseBriqueResponseOptions,
} from "./contracts.js";

export {
  createCapabilityClient,
  type CapabilityClient,
  type CapabilityResult,
  // shared semantic types
  type MeaningDescriptor,
  type MeaningSection,
  type FunctionalDescriptor,
  type FlowStep,
  type FunctionalFlowNode,
  type DataDescriptor,
  type MatterDescriptor,
  type StructureNode,
  type StructurePatch,
  type TraceEvent,
  type TraceFacets,
  type TraceFacetNode,
  type TraceFilters,
  type TraceTimeRange,
  type WrapperSnapshot,
  type VocabularyAxis,
  type VocabularyPatch,
  type CapabilityMeaningQueryFilter,
  type ReadMeaningInputItem,
  type ReadMeaningResultItem,
  type MeaningQueryResultItem,
  type StateContextDescriptor,
  type EditCreateItem,
  type EditDeleteItem,
  type EditDuplicateItem,
  type EditPatchMeaningItem,
  // params
  type EditCreateParams,
  type EditDeleteParams,
  type EditDuplicateParams,
  type EditGetElementTemplateParams,
  type EditPatchMeaningParams,
  type MeaningQueryParams,
  type MeaningRebuildParams,
  type MeaningUpdateParams,
  type ReadDocumentParams,
  type ReadMeaningParams,
  type ReadStateParams,
  type ReadStructureParams,
  type TraceInspectParams,
  type VocabularyDeleteParams,
  type VocabularyGetParams,
  type VocabularyPatchParams,
  type VocabularyQueryParams,
  type MatterCloneParams,
  type MatterCreateParams,
  type MatterDeleteParams,
  type MatterDeriveParams,
  type MatterExistsParams,
  type MatterReadParams,
  type MatterReadBatchParams,
  type MatterSubscribeParams,
  type MatterUnsubscribeParams,
  type MatterWriteParams,
  type StructureCloneParams,
  type StructureCreateParams,
  type StructureDeleteParams,
  type StructureDeriveParams,
  type StructurePatchParams,
  type StructureReadParams,
  // payloads
  type EditCreatePayload,
  type EditDeletePayload,
  type EditDuplicatePayload,
  type EditGetElementTemplatePayload,
  type EditPatchMeaningPayload,
  type MeaningQueryPayload,
  type MeaningRebuildPayload,
  type MeaningUpdatePayload,
  type ReadDocumentPayload,
  type ReadMeaningPayload,
  type ReadStatePayload,
  type ReadStructurePayload,
  type TraceInspectPayload,
  type VocabularyDeletePayload,
  type VocabularyGetPayload,
  type VocabularyPatchPayload,
  type VocabularyQueryPayload,
  type MatterClonePayload,
  type MatterCreatePayload,
  type MatterDeletePayload,
  type MatterDerivePayload,
  type MatterExistsPayload,
  type MatterReadPayload,
  type MatterReadBatchPayload,
  type MatterSubscribePayload,
  type MatterUnsubscribePayload,
  type MatterWritePayload,
  type StructureClonePayload,
  type StructureCreatePayload,
  type StructureDeletePayload,
  type StructureDerivePayload,
  type StructurePatchPayload,
  type StructureReadPayload,
} from "./typed.js";
